repositories:
- name: stable
  url: https://charts.helm.sh/stable/
- name: elastic
  url: https://helm.elastic.co
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

  
helmDefaults:
  tillerNamespace: helm
  tillerless: true

environments:
  default:
    values:
      - Namespace: "default"
