apiVersion: v1
kind: Service
metadata:
  name: apm-server-nodeport
spec:
  type: NodePort
  selector:
    app: apm-server # label of the pod
  ports:
    - name: apm
      protocol: TCP
      port: 8200
      targetPort: 8200
      nodePort: 30041